import React from "react";
import Head from "next/head";
import ImageNav from "../../components/ImageNav";

export default function index() {
  return (
    <div>
      <Head>
        <title>Html img etiketi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ImageNav />
        <h1>Html img etiketi</h1>
        <img src="/images/next.png" alt="logo" />
      </main>
    </div>
  );
}
