import React from "react";
import Head from "next/head";

export default function index() {
  return (
    <div>
      <Head>
        <title>optimizasyon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Optimizasyon Page</h1>
        <h3>
          pages klasörü altında optimizasyon klsörüne direk url'den ulaşmak için
          optimizasyon klasörü altında index.js dosyasını tanımlamamız gerekir.
        </h3>
        <h3>
          http://localhost:3000/optimizasyon - bu index.js dosyasını gösterir
        </h3>
      </main>
    </div>
  );
}
