import React from "react";
import Head from "next/head";

export default function index() {
  return (
    <div>
      <Head>
        <title>Refrences</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h3>
            References klasörü altındaki index.js dosyasına sadece references
            yolu belirtilerek Ulaşılabilir.
          </h3>
        </div>
      </main>
    </div>
  );
}
