import Head from "next/head";
import { withRouter } from "next/router";
import styles from "../../styles/Sidebar.module.css";

function withRouters({ router }) {
  return (
    <div>
      <Head>
        <title>Next/Router | withRouter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{router.pathname}</p>
      <hr />
      <button
        className={styles.buton}
        type="button"
        onClick={() => router.push("/router/")}
      >
        Router Home
      </button>
    </div>
  );
}
export default withRouter(withRouters);
