import React from "react";
import Head from "next/head";

export default function About() {
  return (
    <div>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About page</h1>
        <h1>
          pages klasörü altında bulunan about.js dosya yoluyla router işlemi
          gerçekleştirilmiştir.
        </h1>
        <h1>http://localhost:3000/about</h1>
      </main>
    </div>
  );
}
